#! /bin/bash

languages="en-US de zh-TW zh-CN it"
for i in $languages
do
    for j in chrome/locale/$i/*.dtd
    do
        cut -d ' ' -f 2 < $j > /tmp/$i${j##*/}
    done
done

for i in $languages
do
    for j in /tmp/$i*.dtd
    do
        echo "---- $j ----"
        diff ${j/$i/en-US} $j
    done
done
    
