rm personaswitcher.xpi

zip personaswitcher.xpi \
    bootstrap.js \
    install.rdf \
    chrome.manifest \
    chrome/content/about.xul \
    chrome/content/PersonaSwitcher.jsm \
    chrome/content/prefs.js \
    chrome/content/ui.js \
    chrome/locale/en-US/ \
    chrome/locale/en-US/about.dtd \
    chrome/locale/en-US/options.dtd \
    chrome/locale/en-US/personaswitcher.properties \
    chrome/locale/zh-TW/ \
    chrome/locale/zh-TW/about.dtd \
    chrome/locale/zh-TW/options.dtd \
    chrome/locale/zh-TW/personaswitcher.properties \
    chrome/locale/zh-CN/ \
    chrome/locale/zh-CN/about.dtd \
    chrome/locale/zh-CN/options.dtd \
    chrome/locale/zh-CN/personaswitcher.properties \
    chrome/locale/de/ \
    chrome/locale/de/about.dtd \
    chrome/locale/de/options.dtd \
    chrome/locale/de/personaswitcher.properties \
    chrome/locale/it/ \
    chrome/locale/it/about.dtd \
    chrome/locale/it/options.dtd \
    chrome/locale/it/personaswitcher.properties \
    chrome/skin/PersonaSwitcher16.png \
    chrome/skin/PersonaSwitcher24.png \
    chrome/skin/PersonaSwitcher32.png \
    chrome/skin/PersonaSwitcher48.png \
    chrome/skin/PersonaSwitcher64.png \
    chrome/skin/toolbar-button.css \
    webextension/manifest.json \
    webextension/_locales/en-US/messages.json \
    webextension/_locales/zh-TW/messages.json \
    webextension/_locales/zh-CN/messages.json \
    webextension/_locales/de/messages.json \
    webextension/_locales/it/messages.json \
    webextension/background_scripts/WEPersonaSwitcher.js \
    webextension/browser_action/popup.css \
    webextension/browser_action/popup.html \
    webextension/browser_action/popup.js \
    webextension/icons/PersonaSwitcher16.png \
    webextension/icons/PersonaSwitcher24.png \
    webextension/icons/PersonaSwitcher32.png \
    webextension/icons/PersonaSwitcher48.png \
    webextension/icons/PersonaSwitcher64.png \
    webextension/preferences/options.html \
    webextension/preferences/options.js
